### DISCUSSION TITLE
Port forwarding

### DISCUSSION THREAD

**Discussion by Luicosas** [aksiksi/compose2nix#39] [Q&A] [answered]
I'm setting up a wg-easy container and the docker-compose.yml works when I use `podman-compose up -d`, but when I converted it to a docker-compose.nix with `compose2nix` the port forwarding breaks. I'm port forwarding port 51821 so I can go to localhost:51821 to configure wg-easy. I speculate that the firewall isn't allowing systemd services to be port forwarded because they run as root. When I run `sudo su`, then run `podman-compose up -d` the same issue appears (can't connect to localhost:51821). 

Does compose2nix require any changes to networking / firewall settings? I think I'm missing something obvious. 

Here is my docker-compose.yml file:
```
name: 
  wg-easy
services:
  wg-easy:
    environment:
      - LANG=en
      - WG_HOST=luilab.ddns.net
      - WG_ALLOWED_IPS=10.8.1.0/24
      - WG_DEFAULT_DNS=
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - PORT=51821
      - WG_PORT=51820
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - /nixos-data/wg-easy-data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW # Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      internal-net:
        ipv4_address: 10.8.1.1
networks: 
  internal-net: 
    internal: true
    driver: bridge
    ipam: 
      config: 
        - subnet: 10.8.1.0/24
          gateway: 10.8.1.0
```

**Comment by aksiksi** [comment]
That’s strange. This seems firewall related, but that shouldn’t have any impact if accessing the ports locally…

Can you try limiting the ports to localhost? Like this:

`"127.0.0.1:51820:51820/tcp"`

Also, if possible, could you share the output of `sudo iptables --list` for the working and non-working cases?

**Reply by Luicosas** [reply]
I tried limiting it to localhost, the behavior still persists

```
$ podman ps
CONTAINER ID  IMAGE                           COMMAND               CREATED        STATUS        PORTS                                                 NAMES
5fdf81241802  ghcr.io/wg-easy/wg-easy:latest  /usr/bin/dumb-ini...  9 seconds ago  Up 9 seconds  0.0.0.0:51820->51820/udp, 127.0.0.1:51821->51821/tcp  wg-easy
```

When I curl, the request gets sent off but it hangs 
```
curl 127.0.0.1:51821 -v
*   Trying 127.0.0.1:51821...
* Connected to 127.0.0.1 (127.0.0.1) port 51821
> GET / HTTP/1.1
> Host: 127.0.0.1:51821
> User-Agent: curl/8.9.1
> Accept: */*
> 
* Request completely sent off
```

This is my iptables
```
$ sudo iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
nixos-fw   all  --  anywhere             anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain nixos-fw (1 references)
target     prot opt source               destination         
nixos-fw-accept  all  --  anywhere             anywhere            
nixos-fw-accept  all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
nixos-fw-accept  tcp  --  anywhere             anywhere             tcp dpt:51821
nixos-fw-accept  udp  --  anywhere             anywhere             udp dpt:51820
nixos-fw-accept  udp  --  anywhere             anywhere             udp dpt:domain
nixos-fw-accept  icmp --  anywhere             anywhere             icmp echo-request
nixos-fw-log-refuse  all  --  anywhere             anywhere            

Chain nixos-fw-accept (6 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            

Chain nixos-fw-log-refuse (1 references)
target     prot opt source               destination         
LOG        tcp  --  anywhere             anywhere             tcp flags:FIN,SYN,RST,ACK/SYN LOG level info prefix "refused connection: "
nixos-fw-refuse  all  --  anywhere             anywhere             PKTTYPE != unicast
nixos-fw-refuse  all  --  anywhere             anywhere            

Chain nixos-fw-refuse (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere
```

On further inspection, it doesn't seem to be the firewalls fault. I changed my configuration.nix 
```
networking.firewall.enable = false;
```
So iptables is no longer used
```
$ iptables
iptables: command not found
```
But the issue still persists.

**Reply by Luicosas** [reply]
I still have no idea where this issue is coming from but some further details on the problem, the socket on 51821 are being created, they just seem disconnected from the container. 

This is the output from netstat. 
When I podman-compose as root then open localhost:51821 from browser: 
```
$ netstat | grep 51821
tcp        0      0 localhost:39872         localhost:51821         ESTABLISHED
tcp      505      0 localhost:51821         localhost:55740         ESTABLISHED
tcp      409      0 localhost:51821         localhost:39876         ESTABLISHED
tcp      642      0 localhost:51821         localhost:43894         CLOSE_WAIT 
tcp      519      0 localhost:51821         localhost:45452         CLOSE_WAIT 
tcp      519      0 localhost:51821         localhost:45438         CLOSE_WAIT 
tcp      519      0 localhost:51821         localhost:43920         CLOSE_WAIT 
tcp        0      0 localhost:55740         localhost:51821         ESTABLISHED
...
```

When I podman-compose as user then open localhost:51821 in browser:
```
netstat | grep 51821
tcp        0      0 localhost:42568         localhost:51821         ESTABLISHED
tcp        0      0 localhost:51821         localhost:42572         TIME_WAIT  
tcp        0      0 localhost:51821         localhost:42570         TIME_WAIT  
tcp        0      0 localhost:42558         localhost:51821         TIME_WAIT  
tcp        0      0 localhost:51821         localhost:42568         ESTABLISHED
tcp        0      0 localhost:51821         localhost:41494         TIME_WAIT  
tcp        0      0 localhost:51821         localhost:41506         TIME_WAIT  
tcp        0      0 localhost:51821         localhost:42588         TIME_WAIT
```

This with curl being able to send the request off, seems to me that the connection is somehow broken in the middle and not properly passing the packet into the container.

**Reply by Luicosas** [reply]
I've only made a few changes to the default nix system so I'm somewhat thinking of rewriting from a blank compose2nix-network-working system and carrying only the changes I want, like one by one until the networking breaks. Do you normally start from the default nixos config, or something else when setting up a podman container host?

**Reply by aksiksi** [reply]
I think the problem are the `gateway` and `internal` options you've set on the network. Any reason why you're setting these? The [wg-easy sample](https://github.com/wg-easy/wg-easy/blob/master/docker-compose.yml) does not have these set.

I was able to reproduce this using the `nginx` container:

```
$ sudo podman network create internal-net --driver=bridge --subnet=10.8.1.0/24 --gateway=10.8.1.0 --internal
$ sudo podman run -it --name=nginx -p 12345:80 --rm --network internal-net docker.io/library/nginx
```

Cannot connect from host:

```
$ curl 127.0.0.1:12345
```

But I can connect inside the container (no internet access from within though):

```
$ sudo podman exec -it nginx curl 127.0.0.1:80
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

But **without** `gateway` and `internal` set, you can connect from the host:

```
$ sudo podman network create internal-net --driver=bridge --subnet=10.8.1.0/24
```

**Reply by Luicosas** [reply]
I originally set `internal: true` because I wanted to isolate the container from interacting with the internet, the intention was to create a local docker network to put other containers in so I can wireguard into the network and backup my stuff / interact with other services I run on a old laptop.  I thought it would be more secure that way, though I its only a minor concern, I'll probably just turn that setting off for now. Thanks for the help!

**Reply by aksiksi** [reply]
I see. There might be a workaround for that: https://github.com/containers/podman/discussions/21451

There are a ton of questions on this topic on the Podman repo.

**Reply by Luicosas** [reply, marked as answer]
Oh I see, thanks, the workaround worked! got my remote backup working and checked that it can't access the internet. Sorry about not checking the podman discussions first, I thought it was a compose2nix specific issue 😅. 

Posting my final working compose in case anyone else stumbles on this thread. 
```
name: 
  wg-easy
services:
  wg-easy:
    environment:
      - LANG=en
      - WG_HOST=<some-domain-name>
      - WG_ALLOWED_IPS=10.8.1.0/24
      - WG_DEFAULT_DNS=
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - PORT=51821
      - WG_PORT=51820
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - /nixos-data/wg-easy-data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "127.0.0.1:51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW # Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      internal-net:
        ipv4_address: 10.8.1.1
networks: 
  internal-net: 
    driver: bridge
    driver_opts: 
      no_default_route: 1
    ipam: 
      config: 
        - subnet: 10.8.1.0/24
          gateway: 10.8.1.0
 ```
 
Only --internal seems to affect networking and setting gateway is fine. Earlier gateway was being set to one of the ips allocated to the container and that made the networking go wonky.
