### DISCUSSION TITLE
add additional nix options to compose file

### DISCUSSION THREAD

**Discussion by DragonHunter274** [aksiksi/compose2nix#67] [Ideas]
being able to define e.g config files in nix in the docker compose file in specially formatted comments that get copied to the nix file would be really useful

**Comment by aksiksi** [comment]
Can you share a usecase or example of how you imagine this could work?

**Reply by DragonHunter274** [reply]
something like this:

```yaml
# BEGIN NIX

#environment.etc."unbound/conf.d/records.conf".text =''
#local-data: "example.com A 10.1.1.2"
#'';

# END NIX


services:
  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    ports:
      - 53:5335/tcp
      - 53:5335/udp
    volumes:
      - /etc/unbound/conf.d/:/usr/local/unbound/conf.d/:rw
    restart: unless-stopped
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s
```
