### ISSUE TITLE
Nvidia GPU support

### ISSUE THREAD

**Issue by aksiksi** [aksiksi/compose2nix#1]
Some random links:

* Docker Compose `deploy` devices: https://docs.docker.com/compose/compose-file/deploy/#devices
* Podman support for CDI: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html#running-a-workload-with-cdi
* Docker CDI support: https://github.com/docker/cli/issues/3864
* Docker Compose support with Podman: https://github.com/containers/podman/issues/19338

**Comment by aksiksi** [comment]
With CDI support now added to NixOS (https://github.com/NixOS/nixpkgs/pull/284507), GPU access should work in a container. See this thread for details: https://discourse.nixos.org/t/nvidia-gpu-support-in-podman-and-cdi-nvidia-ctk/36286.

### Podman

Add the CDI device(s) to `devices` in your Compose file, like so:

```yaml
jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    security_opt:
      - label=disable
    devices:
      - nvidia.com/gpu=all
```

### Docker

TBA.

**Comment by SpidFightFR** [comment]
Any news on the docker side ? I personally added the CDI devices to my docker compose config, when i run `docker-compose up` it uses my GPU, when i use compose2nix, it gets back on the CPU.

**Comment by aksiksi** [comment]
I personally don’t use Docker. But I did some digging into Docker PRs and found that CDI support is still experimental: https://github.com/moby/moby/pull/47087

To enable it, you’ll first need to set the CDI feature flag: https://docs.docker.com/reference/cli/dockerd/

In your NixOS config, try this:

```
virtualisation.docker.daemon.settings = {
  features = { cdi = true; };
};
```

**Comment by SpidFightFR** [comment]
> I personally don’t use Docker. But I did some digging into Docker PRs and found that CDI support is still experimental: [moby/moby#47087](https://github.com/moby/moby/pull/47087)
> 
> To enable it, you’ll first need to set the CDI feature flag: https://docs.docker.com/reference/cli/dockerd/#enable-cdi-devices
> 
> In your NixOS config, try this:
> 
> ```
> virtualisation.docker.daemon.settings = {
>   features = { cdi = true; };
> };
> ```
> 
> And you will need to of course pass in “devices” in CDI format as part of your Compose config.

I'm trying to do my tests using InvokeAI (that's the only GPU-Docker tool i got rn):

The compose part looks like this:

```
# Copyright (c) 2023 Eugene Brodsky https://github.com/ebr

x-invokeai: &invokeai
    image: "local/invokeai:latest"
    build:
      context: ..
      dockerfile: docker/Dockerfile

    # Create a .env file in the same directory as this docker-compose.yml file
    # and populate it with environment variables. See .env.sample
    env_file:
      - .env

    # variables without a default will automatically inherit from the host environment
    environment:
      # if set, CONTAINER_INVOKEAI_ROOT will override the Invoke runtime directory location *inside* the container
      - INVOKEAI_ROOT=${CONTAINER_INVOKEAI_ROOT:-/invokeai}
      - HF_HOME
    ports:
      - "${INVOKEAI_PORT:-9090}:${INVOKEAI_PORT:-9090}"
    volumes:
      - type: bind
        source: ${HOST_INVOKEAI_ROOT:-${INVOKEAI_ROOT:-~/invokeai}}
        target: ${CONTAINER_INVOKEAI_ROOT:-/invokeai}
        bind:
          create_host_path: true
      - ${HF_HOME:-~/.cache/huggingface}:${HF_HOME:-/invokeai/.cache/huggingface}
    tty: true
    stdin_open: true


services:
  invokeai-cuda:
    <<: *invokeai
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
```

Though the docker config.nix doesn't contain the device part, idk if it was ignored because of an error on my side ?

**Comment by aksiksi** [comment]
No error on your side - compose2nix does not yet support `deploy.resources.reservations.devices`. I can add support for that today but only for CDI - shouldn't be tricky. Will work on a PR now.

Do you have the CDI feature enabled in your Docker config? If not, it's strange how the GPU is detected when running with Docker Compose directly.

Two other minor notes:

* FYI, the Build spec (`build`) is not supported by compose2nix, so you'll need to build the container first. See: https://github.com/aksiksi/compose2nix/issues/4
* `tty` and `stdin_open` are not supported - not sure how critical these are, though.

**Comment by SpidFightFR** [comment]
> I can add support for that today but only for CDI

Sounds great to me !
Thank you for your answers.

> Do you have the CDI feature enabled in your Docker config? If not, it's strange how the GPU is detected when running with Docker Compose directly.

nope, i only got that enabled:
`hardware.nvidia-container-toolkit.enable = true;` on docker 25. Something that was recommended to me on the [nixos discourse](https://discourse.nixos.org/t/nvidia-docker-container-runtime-doesnt-detect-my-gpu/51336/2)

**Comment by aksiksi** [comment]
Ah gotcha, thanks for clarifying! It looks like the feature flag is set by the NixOS module here: https://github.com/NixOS/nixpkgs/blob/nixos-24.05/nixos/modules/services/hardware/nvidia-container-toolkit/default.nix#L72

I'll also update the README with these steps for others who want to get CDI GPU support running in Docker.

**Comment by aksiksi** [comment]
In the meantime, can you please try passing in your devices via the `devices` block like this:

```yaml
services:
  invokeai-cuda:
    <<: *invokeai
    restart: unless-stopped
    devices:
      - nvidia.com/gpu=all
```

The change I am making will be doing exactly this, so you'll just have another way to write it in Compose.
