### ISSUE TITLE
Macvlan Network Support in Compose File

### ISSUE THREAD

**Issue by Underknowledge** [aksiksi/compose2nix#15]
I am currently using compose2nix lift and shift containers over to NixOS and I have a specific use case where I need support for macvlan networks.
The Service relies on using :443 and I quite like my Nginx/smalstep setup.
Below is an example of my compose file:

```yaml
version: '3.7'
services:
  teddycloud:
    container_name: teddycloud
    mac_address: 10:50:02:01:00:02
    dns: 192.168.8.1
    hostname: tc
    image: ghcr.io/toniebox-reverse-engineering/teddycloud:latest
    ports:
     - 80:80
     - 443:443  
    volumes:
      - /opt/tony/certs:/teddycloud/certs
      - /opt/tony/config:/teddycloud/config
      - /opt/tony/content:/teddycloud/data/content
      - /opt/tony/library:/teddycloud/data/library
      - /opt/tony/firmware:/teddycloud/data/firmware
    restart: unless-stopped
    networks:
      homenet:
        ipv4_address: 192.168.8.10

networks:
  homenet:
    driver: macvlan
    driver_opts:
      parent: enp2s0 
    ipam:
      config:
        - subnet: 192.168.8.0/24
          gateway: 192.168.8.1 
```

Thank you for considering and for your awesome effort in maintaining compose2nix!
