### ISSUE TITLE
Bug: volume names aren't properly outputted

### ISSUE THREAD

**Issue by oskardotglobal** [aksiksi/compose2nix#26]
Hi, it's me again with another bug report

Let's say we have the following compose file:
```yaml
name: "example"

volumes:
  test:
  test2:
    name: other_test2
  example_test3:

services:
  app:
    image: hello-world
    volumes:
      - test:/test
      - test2:/test2
      - example_test3:/test3
```

The resulting nix file will contain:
```nix
virtualisation.oci-containers.containers."example-app".volumes = [
      "example_test3:/test3:rw"
      "test:/test:rw"
      "test2:/test2:rw"
];
```

This is incorrect.  
The names of the volumes should be always prefixed with the project name, unless the name property is given (which is an enhancement I understand isn't implemented). In this case, the container will not be able to be created unless the name of the container is set to `<project_name>_<name>`.
