### ISSUE TITLE
Support for Compose Build spec

### ISSUE THREAD

**Issue by aksiksi** [aksiksi/compose2nix#4]
Here: https://docs.docker.com/compose/compose-file/build/

For a Git based build context, the generated Nix derivation needs to:

1. Clone the repo (with a correct hash)
2. Build a Docker imagee

This can be done using [`dockerTools.buildImage`](https://nixos.org/manual/nixpkgs/stable/#ssec-pkgs-dockerTools-buildImage) + [`fetchGit`](https://nixos.org/manual/nix/stable/language/builtins#builtins-fetchGit).

This would then be provided as an input to the generated container using [`imageFile`](https://search.nixos.org/options?channel=23.11&show=virtualisation.oci-containers.containers.<name>.imageFile).

Example of a Compose build service:

```yaml
version: '3.5'
services:
  prefetcharr:
    build: https://github.com/p-hueber/prefetcharr.git
    image: prefetcharr
    environment:
      - JELLYFIN_URL=http://example.com/jellyfin
      - JELLYFIN_API_KEY=<YOUR KEY HERE>
      - SONARR_URL=http://example.com/sonarr
      - SONARR_API_KEY=<YOUR KEY HERE>
      - LOG_DIR=/log
      - RUST_LOG=prefetcharr=debug
    volumes:
      - /path/to/log/dir:/log
```
