### ISSUE TITLE
Control env file behavior per-service

### ISSUE THREAD

**Issue by aksiksi** [aksiksi/compose2nix#51]
We can use Compose labels to control how env files are included at a per-service level:

Example:

```yaml
services:
  abc:
    env_file:
      - ./secret.env
    labels:
      - "compose2nix.settings.envFilesOnly=true"
```
