### ISSUE TITLE
CPU float to --cpu-quota integer

### ISSUE THREAD

**Issue by sebastian9** [aksiksi/compose2nix#55]
I'm getting this error when the service tries to start one of the containers:

` invalid argument "0.5" for "--cpu-quota" flag: strconv.ParseInt: parsing "0.5": invalid syntax`

https://docs.docker.com/engine/containers/resource_constraints/#cpu
https://docs.docker.com/engine/containers/run/#cpu-quota-constraint
https://stackoverflow.com/a/30560046

```yaml
...
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
...
```

```nix
...
    extraOptions = [
      "--cpu-quota=0.5"
...
```

```yaml
networks:
  dawarich:
services:
  dawarich_redis:
    image: redis:7.0-alpine
    command: redis-server
    networks:
      - dawarich
    volumes:
      - shared_data:/var/shared/redis
    restart: always
  dawarich_db:
    image: postgres:14.2-alpine
    container_name: dawarich_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - gem_cache:/usr/local/bundle/gems
      - public:/var/app/public
      - watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      TIME_ZONE: Europe/London
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - dawarich_db
      - dawarich_redis
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - gem_cache:/usr/local/bundle/gems
      - public:/var/app/public
      - watched:/var/app/tmp/imports/watched
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - dawarich_db
      - dawarich_redis
      - dawarich_app
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB

volumes:
  db_data:
  gem_cache:
  shared_data:
  public:
  watched:
```

```nix
# Auto-generated using compose2nix v0.3.1-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."dawarich_app" = {
    image = "freikin/dawarich:latest";
    environment = {
      "APPLICATION_HOST" = "localhost";
      "APPLICATION_HOSTS" = "localhost";
      "APPLICATION_PROTOCOL" = "http";
      "DATABASE_HOST" = "dawarich_db";
      "DATABASE_NAME" = "dawarich_development";
      "DATABASE_PASSWORD" = "password";
      "DATABASE_USERNAME" = "postgres";
      "DISTANCE_UNIT" = "km";
      "MIN_MINUTES_SPENT_IN_CITY" = "60";
      "RAILS_ENV" = "development";
      "REDIS_URL" = "redis://dawarich_redis:6379/0";
      "TIME_ZONE" = "America/Los_Angeles";
    };
    volumes = [
      "dawarichgpstracker_gem_cache:/usr/local/bundle/gems:rw"
      "dawarichgpstracker_public:/var/app/public:rw"
      "dawarichgpstracker_watched:/var/app/tmp/imports/watched:rw"
    ];
    ports = [
      "3000:3000/tcp"
    ];
    cmd = [ "bin/dev" ];
    dependsOn = [
      "dawarich_db"
      "dawarichgpstracker-dawarich_redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cpu-quota=0.5"
      "--entrypoint=[\"dev-entrypoint.sh\"]"
      "--log-opt=max-file=5"
      "--log-opt=max-size=100m"
      "--memory=2147483648b"
      "--network-alias=dawarich_app"
      "--network=dawarichgpstracker_dawarich"
    ];
  };
  systemd.services."docker-dawarich_app" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-dawarichgpstracker_dawarich.service"
      "docker-volume-dawarichgpstracker_gem_cache.service"
      "docker-volume-dawarichgpstracker_public.service"
      "docker-volume-dawarichgpstracker_watched.service"
    ];
    requires = [
      "docker-network-dawarichgpstracker_dawarich.service"
      "docker-volume-dawarichgpstracker_gem_cache.service"
      "docker-volume-dawarichgpstracker_public.service"
      "docker-volume-dawarichgpstracker_watched.service"
    ];
    partOf = [
      "docker-compose-dawarichgpstracker-root.target"
    ];
    wantedBy = [
      "docker-compose-dawarichgpstracker-root.target"
    ];
  };
  virtualisation.oci-containers.containers."dawarich_db" = {
    image = "postgres:14.2-alpine";
    environment = {
      "POSTGRES_PASSWORD" = "password";
      "POSTGRES_USER" = "postgres";
    };
    volumes = [
      "dawarichgpstracker_db_data:/var/lib/postgresql/data:rw"
      "dawarichgpstracker_shared_data:/var/shared:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=dawarich_db"
      "--network=dawarichgpstracker_dawarich"
    ];
  };
  systemd.services."docker-dawarich_db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-dawarichgpstracker_dawarich.service"
      "docker-volume-dawarichgpstracker_db_data.service"
      "docker-volume-dawarichgpstracker_shared_data.service"
    ];
    requires = [
      "docker-network-dawarichgpstracker_dawarich.service"
      "docker-volume-dawarichgpstracker_db_data.service"
      "docker-volume-dawarichgpstracker_shared_data.service"
    ];
    partOf = [
      "docker-compose-dawarichgpstracker-root.target"
    ];
    wantedBy = [
      "docker-compose-dawarichgpstracker-root.target"
    ];
  };
  virtualisation.oci-containers.containers."dawarich_sidekiq" = {
    image = "freikin/dawarich:latest";
    environment = {
      "APPLICATION_HOST" = "localhost";
      "APPLICATION_HOSTS" = "localhost";
      "APPLICATION_PROTOCOL" = "http";
      "BACKGROUND_PROCESSING_CONCURRENCY" = "10";
      "DATABASE_HOST" = "dawarich_db";
      "DATABASE_NAME" = "dawarich_development";
      "DATABASE_PASSWORD" = "password";
      "DATABASE_USERNAME" = "postgres";
      "DISTANCE_UNIT" = "km";
      "RAILS_ENV" = "development";
      "REDIS_URL" = "redis://dawarich_redis:6379/0";
    };
    volumes = [
      "dawarichgpstracker_gem_cache:/usr/local/bundle/gems:rw"
      "dawarichgpstracker_public:/var/app/public:rw"
      "dawarichgpstracker_watched:/var/app/tmp/imports/watched:rw"
    ];
    cmd = [ "sidekiq" ];
    dependsOn = [
      "dawarich_app"
      "dawarich_db"
      "dawarichgpstracker-dawarich_redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cpu-quota=0.5"
      "--entrypoint=[\"dev-entrypoint.sh\"]"
      "--log-opt=max-file=5"
      "--log-opt=max-size=100m"
      "--memory=2147483648b"
      "--network-alias=dawarich_sidekiq"
      "--network=dawarichgpstracker_dawarich"
    ];
  };
  systemd.services."docker-dawarich_sidekiq" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-dawarichgpstracker_dawarich.service"
      "docker-volume-dawarichgpstracker_gem_cache.service"
      "docker-volume-dawarichgpstracker_public.service"
      "docker-volume-dawarichgpstracker_watched.service"
    ];
    requires = [
      "docker-network-dawarichgpstracker_dawarich.service"
      "docker-volume-dawarichgpstracker_gem_cache.service"
      "docker-volume-dawarichgpstracker_public.service"
      "docker-volume-dawarichgpstracker_watched.service"
    ];
    partOf = [
      "docker-compose-dawarichgpstracker-root.target"
    ];
    wantedBy = [
      "docker-compose-dawarichgpstracker-root.target"
    ];
  };
  virtualisation.oci-containers.containers."dawarichgpstracker-dawarich_redis" = {
    image = "redis:7.0-alpine";
    volumes = [
      "dawarichgpstracker_shared_data:/var/shared/redis:rw"
    ];
    cmd = [ "redis-server" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=dawarich_redis"
      "--network=dawarichgpstracker_dawarich"
    ];
  };
  systemd.services."docker-dawarichgpstracker-dawarich_redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-dawarichgpstracker_dawarich.service"
      "docker-volume-dawarichgpstracker_shared_data.service"
    ];
    requires = [
      "docker-network-dawarichgpstracker_dawarich.service"
      "docker-volume-dawarichgpstracker_shared_data.service"
    ];
    partOf = [
      "docker-compose-dawarichgpstracker-root.target"
    ];
    wantedBy = [
      "docker-compose-dawarichgpstracker-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-dawarichgpstracker_dawarich" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f dawarichgpstracker_dawarich";
    };
    script = ''
      docker network inspect dawarichgpstracker_dawarich || docker network create dawarichgpstracker_dawarich
    '';
    partOf = [ "docker-compose-dawarichgpstracker-root.target" ];
    wantedBy = [ "docker-compose-dawarichgpstracker-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-dawarichgpstracker_db_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect dawarichgpstracker_db_data || docker volume create dawarichgpstracker_db_data
    '';
    partOf = [ "docker-compose-dawarichgpstracker-root.target" ];
    wantedBy = [ "docker-compose-dawarichgpstracker-root.target" ];
  };
  systemd.services."docker-volume-dawarichgpstracker_gem_cache" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect dawarichgpstracker_gem_cache || docker volume create dawarichgpstracker_gem_cache
    '';
    partOf = [ "docker-compose-dawarichgpstracker-root.target" ];
    wantedBy = [ "docker-compose-dawarichgpstracker-root.target" ];
  };
  systemd.services."docker-volume-dawarichgpstracker_public" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect dawarichgpstracker_public || docker volume create dawarichgpstracker_public
    '';
    partOf = [ "docker-compose-dawarichgpstracker-root.target" ];
    wantedBy = [ "docker-compose-dawarichgpstracker-root.target" ];
  };
  systemd.services."docker-volume-dawarichgpstracker_shared_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect dawarichgpstracker_shared_data || docker volume create dawarichgpstracker_shared_data
    '';
    partOf = [ "docker-compose-dawarichgpstracker-root.target" ];
    wantedBy = [ "docker-compose-dawarichgpstracker-root.target" ];
  };
  systemd.services."docker-volume-dawarichgpstracker_watched" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect dawarichgpstracker_watched || docker volume create dawarichgpstracker_watched
    '';
    partOf = [ "docker-compose-dawarichgpstracker-root.target" ];
    wantedBy = [ "docker-compose-dawarichgpstracker-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-dawarichgpstracker-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
```
