### ISSUE TITLE
`build` property adds unnecessary `localhost/` prefix to images

### ISSUE THREAD

**Issue by prescientmoon** [aksiksi/compose2nix#60]
Hi! 

I was trying to self host [this project](https://github.com/Oliveriver/5d-diplomacy-with-multiverse-time-travel/blob/main/docker-compose.yml). After some modifications the final `docker-compose.yml` looked like this:
```yml
services:
  frontend:
    build: https://github.com/Oliveriver/5d-diplomacy-with-multiverse-time-travel.git#main:client
    restart: always
  backend:
    build: https://github.com/Oliveriver/5d-diplomacy-with-multiverse-time-travel.git#main:server
    environment:
      - "ConnectionStrings__Database=Server=mssql;Database=diplomacy;User=SA;Password=Passw0rd@;Encrypt=True;TrustServerCertificate=True"
    restart: always
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=y
      - "MSSQL_SA_PASSWORD=Passw0rd@"
```

The ports & volumes are manually configured by me outside the generated file, but that's irrelevant. The generated `.nix` file always has `localhost/` prefixed for the image names it's building:
```nix
  virtualisation.oci-containers.containers."5d-diplomacy-frontend" = {
    image = "localhost/compose2nix-5d-diplomacy-frontend";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=frontend"
      "--network=5d-diplomacy_default"
    ];
  };
```

This fails to run on the docker back end. Manually removing the `localhost/` fixes this issue.
